create database Baithi2
go

Create table NHACUNGCAP(
MANCC char(5) primary key,
TENNCC varchar(50),
QUOCGIA VARCHAR(50),
LOAINCC VARCHAR(50));

CREATE TABLE DUOCPHAM(
MADP CHAR(5) PRIMARY KEY,
TENDP VARCHAR(50),
LOAIDP VARCHAR(50),
GIA MONEY);

CREATE TABLE PHIEUNHAP(
SOPN CHAR(5) PRIMARY KEY,
NGNHAP DATETIME,
MANCC CHAR(5),
LOAINHAP VARCHAR(50)
FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC));

CREATE TABLE CTPN(
SOPN CHAR(5),
MADP CHAR(5),
SOLUONG INT,
PRIMARY KEY(SOPN,MADP),
FOREIGN KEY (SOPN) REFERENCES PHIEUNHAP(SOPN),
FOREIGN KEY (MADP) REFERENCES DUOCPHAM(MADP));

INSERT INTO NHACUNGCAP (MANCC, TENNCC, QUOCGIA, LOAINCC) VALUES
('NCC01', 'Phuc Hung', 'Viet Nam', 'Thuong xuyen'),
('NCC02', 'J. B. Pharmaceuticals', 'India', 'Vang lai'),
('NCC03', 'Sapharco', 'Singapore', 'Vang lai');

INSERT INTO DUOCPHAM (MADP, TENDP, LOAIDP, GIA) VALUES
('DP01', 'Thuoc ho PH', 'Siro', 120000),
('DP02', 'Zecuf Herbal CouchRemedy', 'Vien nen', 200000),
('DP03', 'Cotrim', 'Vien sui', 80000);

INSERT INTO PHIEUNHAP (SOPN, NGNHAP, MANCC, LOAINHAP) VALUES
('00001', '2017-11-22', 'NCC01', 'Noi dia'),
('00002', '2017-12-04', 'NCC03', 'Nhap khau'),
('00003', '2017-12-10', 'NCC02', 'Nhap khau');

INSERT INTO CTPN (SOPN, MADP, SOLUONG) VALUES
('00001', 'DP01', 100),
('00002', 'DP02', 200),
('00003', 'DP03', 543);

CREATE TRIGGER TRG_SIRO
ON DUOCPHAM
AFTER INSERT,UPDATE
AS
BEGIN
    IF EXISTS(SELECT 1
			  from inserted 
			  where LOAIDP='Siro' AND GIA <100000)
    BEGIN
        RAISERROR (N'Giá c?a m?t hàng Siro ph?i l?n h?n 100.000!', 16, 1);
        ROLLBACK TRANSACTION;
    END

select * from PHIEUNHAP
where year(NGNHAP)='2017' AND MONTH(NGNHAP)='12'
ORDER BY NGNHAP ASC;

select top 1 DP.MADP,DP.TENDP, SUM(C.SOLUONG) AS TONGSOLUONG
FROM DUOCPHAM DP 
JOIN CTPN C ON DP.MADP=C.MADP
JOIN PHIEUNHAP PN ON PN.SOPN=C.SOPN
WHERE YEAR(NGNHAP)='2017'	
GROUP BY DP.MADP,DP.TENDP
ORDER BY TONGSOLUONG DESC;



